# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: sampleapp
  namespace: {{ .Release.Namespace }}
spec:
  sso:
    - name: React App Login
      clientId: react-auth
      redirectUris:
        - "https://sampleapp.{{ .Values.domain }}/*"
      enableAuthserviceSelector:
        auth-app: "sampleapp"
  # Customize network policies and expose services via istio
  network:
    expose:
      - description: "expose the api"
        service: sampleapp-api
        podLabels:
          app: sampleapp-api
        gateway: tenant
        host: sampleapp
        port: 8080
        advancedHTTP:
          match:
            - name: API Traffic
              uri:
                prefix: /api
      - description: "expose the ui"
        service: sampleapp-ui
        podLabels:
          app: sampleapp-ui
        gateway: tenant
        host: sampleapp
        port: 8080
        advancedHTTP:
          match:
            - name: All other HTTP Traffic
              uri:
                prefix: /
    allow:
      - direction: Egress
        remoteNamespace: istio-tenant-gateway
        remoteSelector:
          app: tenant-ingressgateway
        selector:
          app: sampleapp-api
        port: 443
        description: "SSO External"    
