# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: sampleapp
  namespace: {{ .Release.Namespace }}
spec:
  # Customize network policies and expose services via istio
  network:
    expose:
      - service: sampleapp
        podLabels:
          app: sampleapp
        gateway: tenant
        host: sampleapp
        port: 8080
