# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
domain: uds.dev

app:
  name: sampleapp

images:
  ui:
    repository: ewyles/sampleapp-ui
    pullPolicy: IfNotPresent
    tag: "latest"
  api:
    repository: ewyles/sampleapp-api
    pullPolicy: IfNotPresent
    tag: "latest"

service:
  type: ClusterIP
  port: 8080
