# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-api"
  labels:
    app.kubernetes.io/name: "{{ .Values.app.name }}-api"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http    
      targetPort: 8080
  selector:
    app: "{{ .Values.app.name }}-api"
